# Site wide configuration

title: music, new media, code
description: "Personal website of Josiah Wolf Oberholtzer"
email: josiah.oberholtzer@gmail.com
locale: en_US
baseurl: https://josiah-wolf-oberholtzer.github.io
github_username: josiah-wolf-oberholtzer
soundcloud_username: josiah-wolf-oberholtzer

# Jekyll configuration

permalink: /:categories/:title/
#lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: pygments