# Site wide configuration

title: music, new media, code
description: "Personal website of Josiah Wolf Oberholtzer"
email: josiah.oberholtzer@gmail.com
locale: en_US
baseurl: http://josiahwolfoberholtzer.com
github_username: josiah-wolf-oberholtzer
soundcloud_username: josiah-wolf-oberholtzer
twitter_username: nphthlm
vimeo_username: josiahwolfoberholtzer
google_analytics: UA-4612344-2

# Jekyll configuration

permalink: /:categories/:title/
#lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: pygments